development-applications:
  schedule: '20 7 * * *'
  dag_owner_name: 'Mackenzie'
  dag_owner_email: 'mackenzie.nichols4@toronto.ca'
  title: Development Applications
  date_published: '2021-12-02 13:57:18.929311'
  refresh_rate: Daily
  dataset_category: Table
  owner_division: City Planning
  owner_section: null
  owner_unit: null
  owner_email: cityplanning@toronto.ca
  civic_issues: null
  topics: null
  tags: 
  - name: development
    vocabulary_id: null
  information_url: https://www.toronto.ca/city-government/planning-development/application-information-centre/?action=init#location=&lat=&lng=&zoom=
  excerpt: This data set on Planning applications is shared with the public through
    the City of Toronto's Application Information Centre.
  limitations: 'Visualization restriction: the visualization tool is not compatible
    with X,Y coordinates. It will not work, unless you covert them into Lat,Long.
    The projection of the X and Y are NAD27.  We will be converting to NAD83 in the
    future. '
  notes: "This dataset lists all currently active (open) and inactive (closed) Community\
    \ Planning applications, Committee of Adjustment applications and Toronto Local\
    \ Appeal Body appeals received by the City between January 1st 2008 till present.\r\
    \n\r\nFor more info, see:\r\n[Application Information Centre](https://www.toronto.ca/aic/)\r\
    \n\r\n\r\n[Development Applications - Development Projects](http://app.toronto.ca/AIC/index.do)\r\
    \n"

  resources:
    # resource name
    Development Applications:
      format: csv
      url: https://opendata.toronto.ca/city.planning/development-applications/development-applications.csv
      attributes:
        - id: "APPLICATION_TYPE"
          type: "text"
          info:
            notes: "2-letter code used to identify the type of application."
        - id: "APPLICATION#"
          type: "text"
          info:
            notes: "The application number provided to applicants to identify their application."
        - id: "STREET_NUM"
          type: "text"
          info:
            notes: "Street address number of the primary address for the application."
        - id: "STREET_NAME"
          type: "text"
          info:
            notes: "Street address name of the primary address for the application."
        - id: "STREET_TYPE"
          type: "text"
          info:
            notes: "Street type of the primary address of the application."
        - id: "STREET_DIRECTION"
          type: "text"
          info:
            notes: "Street direction of the primary address of the application."
        - id: "POSTAL"
          type: "text"
          info:
            notes: "First 3 characters of the postal code of the primary address of the application."
        - id: "DATE_SUBMITTED"
          type: "timestamp"
          format: "%Y-%m-%dT%H:%M:%S"
          info:
            notes: "The submission date of the application."
        - id: "STATUS"
          type: "text"
          info:
            notes: "The internal status of the application in the review process."
        - id: "HEARING_DATE"
          type: "text"
          info:
            notes: ""
        - id: "X"
          type: "text"
          info:
            notes: "The NAD27 x coordinate of the primary address of the application."
        - id: "Y"
          type: "text"
          info:
            notes: "The NAD27 y coordinate of the primary address of the application."
        - id: "DESCRIPTION"
          type: "text"
          info:
            notes: "The written description of the application."
        - id: "REFERENCE_FILE#"
          type: "text"
          info:
            notes: "The reference file number of the application."
        - id: "FOLDERRSN"
          type: "text"
          info:
            notes: "The internal database identifier for the application."
        - id: "WARD_NUMBER"
          type: "text"
          info:
            notes: "The ward number of the primary address of the application."
        - id: "WARD_NAME"
          type: "text"
          info:
            notes: "The name of the ward of the primary address of the application."
        - id: "COMMUNITY_MEETING_DATE"
          type: "timestamp"
          format: "%b %d, %Y"
          info:
            notes: "The date of the community consultation meeting for the application."
        - id: "COMMUNITY_MEETING_TIME"
          type: "text"
          info:
            notes: "The time of the community consultation meeting for the application."
        - id: "COMMUNITY_MEETING_LOCATION"
          type: "text"
          info:
            notes: "The location of the community consultation meeting for the application."
        - id: "APPLICATION_URL"
          type: "text"
          info:
            notes: "The web URL for the AIC application details page for the application."
        - id: "CONTACT_NAME"
          type: "text"
          info:
            notes: "The name of the planner assigned to the application."
        - id: "CONTACT_PHONE"
          type: "text"
          info:
            notes: "The phone number of the planner assigned to the application."
        - id: "CONTACT_EMAIL"
          type: "text"
          info:
            notes: "The email address of the planner assigned to the application."
        - id: "PARENT_FOLDER_NUMBER"
          type: "text"
          info:
            notes: "The application number of the higher-level application associated with this application (if one exists)."
        