- package_id: toronto-economic-bulletin
  files:
    - http://opendata.toronto.ca/economic.development.culture/toronto-economic-bulletin/bulletin_opendata.xlsx
- package_id: outbreaks-in-toronto-healthcare-institutions
  files:
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/outbreaks-in-toronto-readme.xlsx
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2020.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2019.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2018.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2017.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2016.xls
- package_id: building-permits-active-permits
  files:
    - http://opendata.toronto.ca/toronto.building/building-permits-active-permits/activepermits_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-active-permits/activepermits.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-active-permits/BuildingPermitsActiveReadme.xls
- package_id: building-permits-cleared-permits-current-year
  files:
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/clearedpermits2020.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/clearedpermits2020_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/BuildingPermitsClearedReadme.xls
- package_id: lobbyist-registry
  files:
    - http://opendata.toronto.ca/lobbyist.registrar/lobbyist-registry/lobbyactivity.zip
- package_id: municipal-licensing-and-standards-business-licences-and-permits
  files:
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-business-licences-and-permits/business.licences.csv
- package_id: labour-force-survey
  files:
    - http://opendata.toronto.ca/economic.development.culture/labour-force-survey/lfs_ivt_annual.zip
    - http://opendata.toronto.ca/economic.development.culture/labour-force-survey/lfs_ivt_monthly.zip
- package_id: school-safety-zone-watch-your-speed-program-detailed-speed-counts
  files:
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2020.zip
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2019.zip
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2018.zip
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2017.zip
- package_id: mobile-watch-your-speed-program-detailed-speed-counts
  files:
    - http://opendata.toronto.ca/transportation.services/mobile-watch-your-speed-program-detailed-speed-counts/mobile_detailed_2020.zip
    - http://opendata.toronto.ca/transportation.services/mobile-watch-your-speed-program-detailed-speed-counts/mobile_detailed_2019.zip
    - http://opendata.toronto.ca/transportation.services/mobile-watch-your-speed-program-detailed-speed-counts/mobile_detailed_2018.zip
- package_id: building-permits-cleared-permits-prior-years
  files:
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/TBPCleared2001_2014_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/TBPCleared2001_2014.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2012_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2012.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2013_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2013.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2014_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2014.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2015_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2015.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2016_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2016.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2017_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2017.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2018_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2018.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/BuildingPermitsClearedReadme.xls
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2019.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2019_csv.zip
- package_id: ttc-routes-and-schedules
  files:
    - http://opendata.toronto.ca/toronto.transit.commission/ttc-routes-and-schedules/OpenData_TTC_Schedules.zip
- package_id: utility-cut-permits
  files:
    - http://opendata.toronto.ca/transportation/utility.cut.permit/ucp_doc.zip
    - http://opendata.toronto.ca/transportation/utility.cut.permit/ucp.zip
- package_id: property-boundaries
  files:
    - http://opendata.toronto.ca/technology.services/property-boundaries/property_bnds_gcc_wgs84.zip
- package_id: address-points-municipal-toronto-one-address-repository
  files:
    - http://opendata.toronto.ca/technology.services/address-points-municipal-toronto-one-address-repository/municipal-address-points-wgs84-latitude-longitude.zip
- package_id: registered-programs-and-drop-in-courses-offering
  files:
    - http://opendata.toronto.ca/parks.forestry.recreation/registered-programs-and-drop-in-courses-offering/program_offering.zip
- package_id: rain-gauge-locations-and-precipitation
  files:
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2020_csv.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2020_json.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2019_json.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2019_csv.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2018_json.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2018_csv.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2017_json.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2017_csv.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2016_json.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2016_csv.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2015_json.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/rainfall2015_csv.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/raingaugenotes.zip
    - http://opendata.toronto.ca/toronto.water/rain-gauge-locations-and-precipitation/readme.docx
- package_id: committee-of-adjustment-applications
  files:
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/active.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2017.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2016.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2015.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2014.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2013.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2012.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2011.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2010.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2009.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2008.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2007.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2006.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2005.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2004.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2003.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2002.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2001.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/coa_attributes.xlsx
- package_id: municipal-licensing-and-standards-investigation-activity
  files:
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/investigation_readme.xlsx
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/investigation_csv.zip
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/investigation.zip
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/investigation.xsd
- package_id: web-analytics
  files:
    - http://opendata.toronto.ca/city.clerks.office/web-analytics/web_analytics_readme.xlsx
    - http://opendata.toronto.ca/city.clerks.office/web-analytics/web_analytics_monthly_csv.zip
    - http://opendata.toronto.ca/city.clerks.office/web-analytics/web_analytics_weekly_csv.zip
- package_id: licensed-child-care-centres
  files:
    - http://opendata.toronto.ca/childrens.services/licensed-child-care-centres/child-care.csv
- package_id: paramedic-services-incident-data
  files:
    - http://opendata.toronto.ca/it/com/TPS_Incident_Data_2010-2019.xlsx
- package_id: traffic-cameras
  files:
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.csv
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.xsd
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.json
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcamerassn.json
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.xml
- package_id: head-of-household
  files:
    - http://opendata.toronto.ca/employment.social/head.household/opendata_tess_ow.zip
    - http://opendata.toronto.ca/employment.social/head.household/tess_ow_split_files.zip
- package_id: 3d-massing
  files:
    - http://opendata.toronto.ca/planning/3dmassing/3DContextMassing_Tile_Locator.pdf
    - http://opendata.toronto.ca/planning/3dmassing/3DMassingShapefile_2019_WGS84.zip
    - http://opendata.toronto.ca/planning/3dmassing/3DMassingMultipatch_2019_WGS84.zip
- package_id: clerk-s-directory-of-record-for-record-series-management-tool-rsmt
  files:
    - http://opendata.toronto.ca/clerk/rsmt/rsmtDirectoryOfRecords.xml
- package_id: clerks-record-classification-system-authoritative-source-rsmt
  files:
    - http://opendata.toronto.ca/clerk/rsmt/rsmtRcsAuthoritative.xml
- package_id: clerks-record-classification-system-internally-approved-rsmt
  files:
    - http://opendata.toronto.ca/clerk/rsmt/rsmtRcsInternal.xml
- package_id: triangular-irregular-network-tin
  files:
    - http://opendata.toronto.ca/gcc/polytin_north_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_south_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_west_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_east2_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_east1_mtm3.zip
- package_id: pcard-expenditures
  files:
    - http://opendata.toronto.ca/accounting/pcard/expenditures.zip
- package_id: parking-ticket-trials
  files:
    - http://opendata.toronto.ca/revenue/parking/trial/Parking_Ticket_Trials.zip
- package_id: non-regulated-lead-sample
  files:
    - http://opendata.toronto.ca/water/lead.sampling/NonRegulatedLeadSampling2011-2013.zip
    - http://opendata.toronto.ca/water/lead.sampling/leadsampling_csv.zip
    - http://opendata.toronto.ca/water/lead.sampling/leadsampling_xml.zip
