toronto-economic-bulletin:
    - http://opendata.toronto.ca/economic.development.culture/toronto-economic-bulletin/bulletin_opendata.xlsx
outbreaks-in-toronto-healthcare-institutions:
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/outbreaks-in-toronto-readme.xlsx
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2020.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2019.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2018.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2017.xls
    - http://opendata.toronto.ca/toronto.public.health/outbreaks-in-toronto-healthcare-institutions/ob_report_2016.xls
building-permits-active-permits:
    - http://opendata.toronto.ca/toronto.building/building-permits-active-permits/activepermits_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-active-permits/activepermits.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-active-permits/BuildingPermitsActiveReadme.xls
building-permits-cleared-permits-current-year:
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/clearedpermits2020.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/clearedpermits2020_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/BuildingPermitsClearedReadme.xls
lobbyist-registry:
    - http://opendata.toronto.ca/lobbyist.registrar/lobbyist-registry/lobbyactivity.zip
municipal-licensing-and-standards-business-licences-and-permits:
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-business-licences-and-permits/business.licences.csv
labour-force-survey:
    - http://opendata.toronto.ca/economic.development.culture/labour-force-survey/lfs_ivt_annual.zip
    - http://opendata.toronto.ca/economic.development.culture/labour-force-survey/lfs_ivt_monthly.zip
school-safety-zone-watch-your-speed-program-detailed-speed-counts:
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2020.zip
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2019.zip
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2018.zip
    - http://opendata.toronto.ca/transportation.services/safety-zone-watch-your-speed-program-detailed-speed-counts/stationary_detailed_2017.zip
mobile-watch-your-speed-program-detailed-speed-counts:
    - http://opendata.toronto.ca/transportation.services/mobile-watch-your-speed-program-detailed-speed-counts/mobile_detailed_2020.zip
    - http://opendata.toronto.ca/transportation.services/mobile-watch-your-speed-program-detailed-speed-counts/mobile_detailed_2019.zip
    - http://opendata.toronto.ca/transportation.services/mobile-watch-your-speed-program-detailed-speed-counts/mobile_detailed_2018.zip
building-permits-cleared-permits-prior-years:
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/TBPCleared2001_2014_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/TBPCleared2001_2014.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2012_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2012.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2013_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2013.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2014_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2014.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2015_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2015.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2016_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2016.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2017_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2017.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2018_csv.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2018.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-current-year/BuildingPermitsClearedReadme.xls
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2019.zip
    - http://opendata.toronto.ca/toronto.building/building-permits-cleared-permits-prior-years/clearedpermits2019_csv.zip
ttc-routes-and-schedules:
    - http://opendata.toronto.ca/toronto.transit.commission/ttc-routes-and-schedules/OpenData_TTC_Schedules.zip
utility-cut-permits:
    - http://opendata.toronto.ca/transportation/utility.cut.permit/ucp_doc.zip
    - http://opendata.toronto.ca/transportation/utility.cut.permit/ucp.zip
property-boundaries:
    - http://opendata.toronto.ca/technology.services/property-boundaries/property_bnds_gcc_wgs84.zip
    - http://opendata.toronto.ca/technology.services/property-boundaries/PROPERTY_BOUNDARIES_WGS84_geojson.zip
address-points-municipal-toronto-one-address-repository:
    - http://opendata.toronto.ca/technology.services/address-points-municipal-toronto-one-address-repository/municipal-address-points-wgs84-latitude-longitude.zip
    - http://opendata.toronto.ca/technology.services/address-points-municipal-toronto-one-address-repository/ADDRESS_POINT_WGS84_geojson.zip
registered-programs-and-drop-in-courses-offering:
    - http://opendata.toronto.ca/parks.forestry.recreation/registered-programs-and-drop-in-courses-offering/program_offering.zip
committee-of-adjustment-applications:
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/active.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2017.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2016.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2015.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2014.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2013.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2012.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2011.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2010.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2009.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2008.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2007.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2006.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2005.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2004.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2003.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2002.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/closed_2001.zip
    - http://opendata.toronto.ca/city.planning/committee-of-adjustment-applications/coa_attributes.xlsx
municipal-licensing-and-standards-investigation-activity:
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/investigation_readme.xlsx
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/MLS_Investigations_csv.zip
    - http://opendata.toronto.ca/municipal.licensing.standards/municipal-licensing-and-standards-investigation-activity/MLS_Investigations_json.zip
web-analytics:
    - http://opendata.toronto.ca/city.clerks.office/web-analytics/web_analytics_readme.xlsx
    - http://opendata.toronto.ca/city.clerks.office/web-analytics/web_analytics_monthly_csv.zip
    - http://opendata.toronto.ca/city.clerks.office/web-analytics/web_analytics_weekly_csv.zip
licensed-child-care-centres:
    - http://opendata.toronto.ca/childrens.services/licensed-child-care-centres/child-care.csv
paramedic-services-incident-data:
    - http://opendata.toronto.ca/it/com/TPS_Incident_Data_2010-2019.xlsx
traffic-cameras:
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.csv
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.xsd
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.json
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcamerassn.json
    - http://opendata.toronto.ca/transportation/tmc/rescucameraimages/Data/tmcearthcameras.xml
head-of-household:
    - http://opendata.toronto.ca/employment.social/head.household/opendata_tess_ow.zip
    - http://opendata.toronto.ca/employment.social/head.household/tess_ow_split_files.zip
3d-massing:
    - http://opendata.toronto.ca/planning/3dmassing/3DContextMassing_Tile_Locator.pdf
    - http://opendata.toronto.ca/city.planning/3d-massing/2020/3DMassingShapefile_2020_WGS84.zip
    - http://opendata.toronto.ca/city.planning/3d-massing/2020/3DMassingMultipatch_2020_WGS84.zip
clerk-s-directory-of-record-for-record-series-management-tool-rsmt:
    - http://opendata.toronto.ca/clerk/rsmt/rsmtDirectoryOfRecords.xml
clerks-record-classification-system-authoritative-source-rsmt:
    - http://opendata.toronto.ca/clerk/rsmt/rsmtRcsAuthoritative.xml
clerks-record-classification-system-internally-approved-rsmt:
    - http://opendata.toronto.ca/clerk/rsmt/rsmtRcsInternal.xml
triangular-irregular-network-tin:
    - http://opendata.toronto.ca/gcc/polytin_north_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_south_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_west_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_east2_mtm3.zip
    - http://opendata.toronto.ca/gcc/polytin_east1_mtm3.zip
pcard-expenditures:
    - http://opendata.toronto.ca/accounting/pcard/expenditures.zip
parking-ticket-trials:
    - http://opendata.toronto.ca/revenue/parking/trial/Parking_Ticket_Trials.zip
non-regulated-lead-sample:
    - http://opendata.toronto.ca/water/lead.sampling/NonRegulatedLeadSampling2011-2013.zip
    - http://opendata.toronto.ca/water/lead.sampling/leadsampling_csv.zip
    - http://opendata.toronto.ca/water/lead.sampling/leadsampling_xml.zip
toronto-centreline-tcl:
    - http://opendata.toronto.ca/technology.services/toronto-centreline-tcl/centreline_wgs84.zip
    - http://opendata.toronto.ca/technology.services/toronto-centreline-tcl/centreline_wgs84_geojson.zip
